[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "44net"
authors = [{name = "Adam Lewis", email = "i fo@airgapped.io"}]
dynamic = ["version", "description"]
